<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tickety.Modules.Events.Application\Tickety.Modules.Events.Application.csproj" />
    <ProjectReference Include="..\Tickety.Modules.Events.Contracts\Tickety.Modules.Events.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

</Project>
